In [1]:
from numpy import *

`numpy.arange` is a function to create an array similar to `list(range)`.

In [2]:
a = arange(4) # array range
a

array([0, 1, 2, 3])

In [3]:
a = arange(0, 4.0, 0.5) # array range
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

Now we change the 0th element of `a` to 5.

In [4]:
a[0] = 5
a

array([5. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

We could also create a `numpy.array` from an existing `list` or `range`.

In [5]:
b = array(range(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The following expression returns a new array with the square values of the elements, from the 1st to the one before the last element.

In [6]:
a[1:-1]**2

array([0.25, 1.  , 2.25, 4.  , 6.25, 9.  ])

We can also change the last element to 100.

In [7]:
a[-1] = 100
a

array([  5. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. , 100. ])

Here we multipying the elements from the 5th to the end, by 0.5.

In [8]:
a[5:] *= 0.5
a

array([ 5.  ,  0.5 ,  1.  ,  1.5 ,  2.  ,  1.25,  1.5 , 50.  ])

Here we add `a` from the 0th to the one before the last element by `b` from the last 7th element to the end. This expression returns a new array with the result of addition.

In [9]:
a[:-1] + b[-7:]

array([ 8.  ,  4.5 ,  6.  ,  7.5 ,  9.  ,  9.25, 10.5 ])